# Generated by Django 5.2.4 on 2026-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('question', models.TextField(blank=True, verbose_name='Вопрос')),
                ('agree_to_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка на контакт',
                'verbose_name_plural': 'Заявки на контакт',
                'ordering': ['-created_at'],
            },
        ),
    ]
