# Generated by Django 5.2.4 on 2026-01-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, upload_to='news', verbose_name='Изображение')),
                ('read_time', models.IntegerField(default=5, verbose_name='Время чтения (мин)')),
                ('category', models.CharField(choices=[('news', 'Новости компании'), ('promo', 'Акции и скидки'), ('event', 'Мероприятия'), ('tips', 'Советы по уходу'), ('new', 'Новинки')], default='news', max_length=20, verbose_name='Категория')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
